Update action

diff --git a/add-issues-to-project/action.yml b/add-issues-to-project/action.yml
--- a/add-issues-to-project/action.yml
+++ b/add-issues-to-project/action.yml
@@ -1,19 +1,23 @@
 name: "Add Issues to Project"
 description: "Adds issues from a specified repository to a specified GitHub Project."
-author: "SATVILab"
+author: "MiguelRodo"
 inputs:
   project_name:
-    description: "Name of the project to which issues should be added"
-    required: true
-    default: ""
-  org_name:
-    description: "Name of the organization (if the project is an organization project)"
+    description: "Name of the project to which issues should be added. Defaults to `source_repo_name`."
     required: false
-    default: "SATVILab"
-  source_repo:
-    description: "Repository from which to fetch issues (format: owner/repo). Defaults to the current repository."
+  project_owner:
+    description: "Owner of the project to which issues should be added. Defaults to `source_repo_owner`."
     required: false
-    default: "${{ github.repository }}"
+  is_project_owner_org:
+    description: "Whether the project owner is an organization. Defaults to `false`."
+    required: false
+    default: "false"
+  source_repo_name:
+    description: "Name of the repository from which to fetch issues. Defaults to current repository."
+    required: false
+  source_repo_owner:
+    description: "Owner of the repository from which to fetch issues. Defaults to current GitHub user."
+    required: false
   ADD_ISSUES_TO_PROJECT_TOKEN:
     description: "GitHub token with correct access for accessing issues and writing to projects"
     required: true
@@ -41,45 +45,99 @@ runs:
     - name: Install gh-projects extension
       shell: bash
       run: gh extension install github/gh-projects
+    
+    - name: Validate input and format used values
+      env:
+        PROJECT_NAME: "${{ inputs.project_name }}"
+        PROJECT_OWNER: "${{ inputs.project_owner }}"
+        IS_PROJECT_OWNER_ORG: "${{ inputs.is_project_owner_org }}"
+        SOURCE_REPO_NAME: "${{ inputs.source_repo_name }}"
+        SOURCE_REPO_OWNER: "${{ inputs.source_repo_owner }}"
+      run: |
+        if [ -z "${SOURCE_REPO_NAME}" ]; then
+          SOURCE_REPO_NAME=$(basename "$(pwd)")
+        fi
+        if [ -z "${PROJECT_NAME}" ]; then
+          PROJECT_NAME_FINAL="$SOURCE_REPO_NAME"
+        else
+          PROJECT_NAME_FINAL="$PROJECT_NAME"
+        fi
+        if [ -z "${SOURCE_REPO_OWNER}" ]; then
+          SOURCE_REPO_OWNER=$(gh api user --jq '.login')
+        fi
+        if [ -z "${PROJECT_OWNER}" ]; then
+          PROJECT_OWNER_FINAL="$SOURCE_REPO_OWNER"
+        else
+          PROJECT_OWNER_FINAL="$PROJECT_OWNER"
+        fi
+        SOURCE_REPO="${SOURCE_REPO_OWNER}/${SOURCE_REPO_NAME}"
+
+        # validate source repo format
+        if [[ ! "$SOURCE_REPO" =~ ^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$ ]]; then
+          echo "Error: Invalid source repository format. Expected format: owner/repo."
+          exit 1
+        fi
+
+        # check that owners exist
+        if [ "${IS_PROJECT_OWNER_ORG}" = "true" ]; then
+          gh api orgs/"${PROJECT_OWNER_FINAL}" > /dev/null
+          if [ $? -ne 0 ]; then
+            echo "Error: Organization '${PROJECT_OWNER_FINAL}' not found."
+            exit 1
+          fi
+        else
+          gh api users/"${PROJECT_OWNER_FINAL}" > /dev/null
+          if [ $? -ne 0 ]; then
+            echo "Error: User '${PROJECT_OWNER_FINAL}' not found."
+            exit 1
+          fi
+        fi
+
+        # check that repo exists
+        gh api repos/"${SOURCE_REPO}" > /dev/null
+        if [ $? -ne 0 ]; then
+          echo "Error: Repository '${SOURCE_REPO}' not found."
+          exit 1
+        fi
+
+        echo "project_name=${PROJECT_NAME_FINAL}" >> $GITHUB_ENV
+        echo "project_owner=${PROJECT_OWNER_FINAL}" >> $GITHUB_ENV
+        echo "source_repo=${SOURCE_REPO}" >> $GITHUB_ENV
 
     - name: Get project ID
       id: get-project-id
       shell: bash
       env:
-        PROJECT_NAME: "${{ inputs.project_name }}"
-        ORG_NAME: "${{ inputs.org_name }}"
+        PROJECT_NAME: "${{ env.project_name }}"
+        PROJECT_OWNER: "${{ env.project_owner }}"
+        IS_PROJECT_OWNER_ORG: "${{ inputs.is_project_owner_org }}"
       run: |
-        if [ -z "${ORG_NAME}" ]; then
-          project_number=$(gh projects list --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .number')
-          project_id=$(gh projects list --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id')
+        if [ "${IS_PROJECT_OWNER_ORG}" = "true" ]; then
+          project_id=$(gh projects list --org "${PROJECT_OWNER}" --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id')
+          if [ -z "$project_id" ]; then
+            echo "Error: Project '${PROJECT_NAME}' not found for owner '${PROJECT_OWNER}' (an organisation)."
+            exit 1
+          fi
         else
-          project_number=$(gh projects list --org "${ORG_NAME}" --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .number')
-          project_id=$(gh projects list --org "${ORG_NAME}" --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id')
+          project_id=$(gh projects list --format json --user "${PROJECT_OWNER}" | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id')
+          if [ -z "$project_id" ]; then
+            echo "Error: Project '${PROJECT_NAME}' not found for owner '${PROJECT_OWNER}' (not an organisation)."
+            exit 1
+          fi
         fi
-
-        if [ -z "${project_number}" ] || [ -z "${project_id}" ]; then
-          echo "Error: Project '${PROJECT_NAME}' not found."
-          exit 1
-        fi
-
-        echo "project_number=${project_number}" >> $GITHUB_ENV
         echo "project_id=${project_id}" >> $GITHUB_ENV
-
-    - name: Validate source_repo format
-      shell: bash
-      run: |
-        if [[ ! "${{ inputs.source_repo }}" =~ ^[^/]+/[^/]+$ ]]; then
-          echo "Error: 'source_repo' must be in the format 'owner/repo'."
-          exit 1
-        fi
 
     - name: Get issues from source repository
       id: get-issues
       shell: bash
       env:
-        SOURCE_REPO: "${{ inputs.source_repo }}"
+        SOURCE_REPO: "${{ env.source_repo }}"
       run: |
         issues=$(gh issue list --repo "${SOURCE_REPO}" --limit 9999 --json number --jq '.[].number' | tr '\n' ' ')
+        if [ -z "$issues" ]; then
+          echo "No issues found in repository '${SOURCE_REPO}'."
+          exit 0
+        fi
         echo "issues=$issues" >> $GITHUB_ENV
 
     - name: Add issues to project if not already present
@@ -88,7 +146,7 @@ runs:
         ISSUES: "${{ env.issues }}"
         ADD_ISSUES_TO_PROJECT_TOKEN: "${{ inputs.ADD_ISSUES_TO_PROJECT_TOKEN }}"
         PROJECT_ID: "${{ env.project_id }}"
-        SOURCE_REPO: "${{ inputs.source_repo }}"
+        SOURCE_REPO: "${{ env.source_repo }}"
       run: |
         existing_issue_ids=()
         has_next_page=true
