Exit if no token provided

diff --git a/add-issues-to-project/action.yml b/add-issues-to-project/action.yml
--- a/add-issues-to-project/action.yml
+++ b/add-issues-to-project/action.yml
@@ -41,6 +41,10 @@ runs:
       run: |
         unset GITHUB_TOKEN
         unset GH_TOKEN
+        if [ -z "$PROJECT_TOKEN" ]; then
+          echo "Error: No token provided."
+          exit 1
+        fi
         echo "$PROJECT_TOKEN" | gh auth login -h github.com --with-token
 
     - name: Install gh-projects extension
